"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.add_card_session_params import AddCardSessionParams
from openapi_client.model.country_alpha2_code import CountryAlpha2Code
globals()['AddCardSessionParams'] = AddCardSessionParams
globals()['CountryAlpha2Code'] = CountryAlpha2Code
from openapi_client.model.session_link_params import SessionLinkParams


class TestSessionLinkParams(unittest.TestCase):
    """SessionLinkParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionLinkParams(self):
        """Test SessionLinkParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SessionLinkParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
