"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.add_bank_account_params_base import AddBankAccountParamsBase


class TestAddBankAccountParamsBase(unittest.TestCase):
    """AddBankAccountParamsBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddBankAccountParamsBase(self):
        """Test AddBankAccountParamsBase"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddBankAccountParamsBase()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
