"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.omit_operation_detail_response_id_or_type_or_show_warning_screen import OmitOperationDetailResponseIdOrTypeOrShowWarningScreen


class TestOmitOperationDetailResponseIdOrTypeOrShowWarningScreen(unittest.TestCase):
    """OmitOperationDetailResponseIdOrTypeOrShowWarningScreen unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOmitOperationDetailResponseIdOrTypeOrShowWarningScreen(self):
        """Test OmitOperationDetailResponseIdOrTypeOrShowWarningScreen"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OmitOperationDetailResponseIdOrTypeOrShowWarningScreen()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
