"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.pick_cip_exclude_keyof_cipid_or_attemps_or_is_valid_ofac_lola_cip import PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP


class TestPickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP(unittest.TestCase):
    """PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP(self):
        """Test PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
