"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.i_phone_info_carrier import IPhoneInfoCarrier
globals()['IPhoneInfoCarrier'] = IPhoneInfoCarrier
from openapi_client.model.i_phone_info import IPhoneInfo


class TestIPhoneInfo(unittest.TestCase):
    """IPhoneInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIPhoneInfo(self):
        """Test IPhoneInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IPhoneInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
