"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.inline_response500 import InlineResponse500


class TestInlineResponse500(unittest.TestCase):
    """InlineResponse500 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse500(self):
        """Test InlineResponse500"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse500()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
