"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.validate_phone_number_request import ValidatePhoneNumberRequest


class TestValidatePhoneNumberRequest(unittest.TestCase):
    """ValidatePhoneNumberRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValidatePhoneNumberRequest(self):
        """Test ValidatePhoneNumberRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ValidatePhoneNumberRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
