"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.user_document import UserDocument
globals()['UserDocument'] = UserDocument
from openapi_client.model.perform_resubmit_upgrade_level_params import PerformResubmitUpgradeLevelParams


class TestPerformResubmitUpgradeLevelParams(unittest.TestCase):
    """PerformResubmitUpgradeLevelParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPerformResubmitUpgradeLevelParams(self):
        """Test PerformResubmitUpgradeLevelParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PerformResubmitUpgradeLevelParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
