"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.pick_validate_otp_params_exclude_keyof_validate_otp_params_device_id import PickValidateOTPParamsExcludeKeyofValidateOTPParamsDeviceId


class TestPickValidateOTPParamsExcludeKeyofValidateOTPParamsDeviceId(unittest.TestCase):
    """PickValidateOTPParamsExcludeKeyofValidateOTPParamsDeviceId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPickValidateOTPParamsExcludeKeyofValidateOTPParamsDeviceId(self):
        """Test PickValidateOTPParamsExcludeKeyofValidateOTPParamsDeviceId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PickValidateOTPParamsExcludeKeyofValidateOTPParamsDeviceId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
