"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.errors_cip_process import ErrorsCIPProcess
from openapi_client.model.level_status import LevelStatus
from openapi_client.model.level_status_detail import LevelStatusDetail
from openapi_client.model.pick_cip_exclude_keyof_cipid_or_attemps_or_is_valid_ofac_lola_cip import PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP
globals()['ErrorsCIPProcess'] = ErrorsCIPProcess
globals()['LevelStatus'] = LevelStatus
globals()['LevelStatusDetail'] = LevelStatusDetail
globals()['PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP'] = PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP
from openapi_client.model.pick_cip_exclude_keyof_cipid_or_attemps_or_is_valid_ofac import PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC


class TestPickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC(unittest.TestCase):
    """PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC(self):
        """Test PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
