"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.attachment_responses import AttachmentResponses
from openapi_client.model.base_identity import BaseIdentity
globals()['AttachmentResponses'] = AttachmentResponses
globals()['BaseIdentity'] = BaseIdentity
from openapi_client.model.scan_identity_response import ScanIdentityResponse


class TestScanIdentityResponse(unittest.TestCase):
    """ScanIdentityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScanIdentityResponse(self):
        """Test ScanIdentityResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScanIdentityResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
