"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.raa_s_payment_method import RaaSPaymentMethod
from openapi_client.model.request_money_base import RequestMoneyBase
from openapi_client.model.request_money_params_all_of import RequestMoneyParamsAllOf
globals()['RaaSPaymentMethod'] = RaaSPaymentMethod
globals()['RequestMoneyBase'] = RequestMoneyBase
globals()['RequestMoneyParamsAllOf'] = RequestMoneyParamsAllOf
from openapi_client.model.request_money_params import RequestMoneyParams


class TestRequestMoneyParams(unittest.TestCase):
    """RequestMoneyParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestMoneyParams(self):
        """Test RequestMoneyParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestMoneyParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
