"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.raa_s_payment_method import RaaSPaymentMethod
from openapi_client.model.send_money_base import SendMoneyBase
from openapi_client.model.send_money_params_all_of import SendMoneyParamsAllOf
globals()['RaaSPaymentMethod'] = RaaSPaymentMethod
globals()['SendMoneyBase'] = SendMoneyBase
globals()['SendMoneyParamsAllOf'] = SendMoneyParamsAllOf
from openapi_client.model.send_money_params import SendMoneyParams


class TestSendMoneyParams(unittest.TestCase):
    """SendMoneyParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendMoneyParams(self):
        """Test SendMoneyParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendMoneyParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
