"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_user_token400_response import GetUserToken400Response


class TestGetUserToken400Response(unittest.TestCase):
    """GetUserToken400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetUserToken400Response(self):
        """Test GetUserToken400Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetUserToken400Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
