"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.operation_data import OperationData
globals()['OperationData'] = OperationData
from openapi_client.model.request_money_response import RequestMoneyResponse


class TestRequestMoneyResponse(unittest.TestCase):
    """RequestMoneyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestMoneyResponse(self):
        """Test RequestMoneyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestMoneyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
