"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.level_one_params_requst import LevelOneParamsRequst


class TestLevelOneParamsRequst(unittest.TestCase):
    """LevelOneParamsRequst unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLevelOneParamsRequst(self):
        """Test LevelOneParamsRequst"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LevelOneParamsRequst()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
