"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ignored_operation_data import IgnoredOperationData
from openapi_client.model.operation_user_detail import OperationUserDetail
from openapi_client.model.payment_method_response import PaymentMethodResponse
globals()['IgnoredOperationData'] = IgnoredOperationData
globals()['OperationUserDetail'] = OperationUserDetail
globals()['PaymentMethodResponse'] = PaymentMethodResponse
from openapi_client.model.pick_operation_detail_response_exclude_keyof_operation_detail_response_id_or_type_or_show_warning_screen import PickOperationDetailResponseExcludeKeyofOperationDetailResponseIdOrTypeOrShowWarningScreen


class TestPickOperationDetailResponseExcludeKeyofOperationDetailResponseIdOrTypeOrShowWarningScreen(unittest.TestCase):
    """PickOperationDetailResponseExcludeKeyofOperationDetailResponseIdOrTypeOrShowWarningScreen unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPickOperationDetailResponseExcludeKeyofOperationDetailResponseIdOrTypeOrShowWarningScreen(self):
        """Test PickOperationDetailResponseExcludeKeyofOperationDetailResponseIdOrTypeOrShowWarningScreen"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PickOperationDetailResponseExcludeKeyofOperationDetailResponseIdOrTypeOrShowWarningScreen()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
