"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.validate_otp403_response import ValidateOTP403Response


class TestValidateOTP403Response(unittest.TestCase):
    """ValidateOTP403Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValidateOTP403Response(self):
        """Test ValidateOTP403Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ValidateOTP403Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
