"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cash_operators_params_base import CashOperatorsParamsBase


class TestCashOperatorsParamsBase(unittest.TestCase):
    """CashOperatorsParamsBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCashOperatorsParamsBase(self):
        """Test CashOperatorsParamsBase"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CashOperatorsParamsBase()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
