"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.raas_quote_transaction_response import RaasQuoteTransactionResponse


class TestRaasQuoteTransactionResponse(unittest.TestCase):
    """RaasQuoteTransactionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRaasQuoteTransactionResponse(self):
        """Test RaasQuoteTransactionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RaasQuoteTransactionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
