"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.available_payment_methods import AvailablePaymentMethods
globals()['AvailablePaymentMethods'] = AvailablePaymentMethods
from openapi_client.model.corridor_dto import CorridorDTO


class TestCorridorDTO(unittest.TestCase):
    """CorridorDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCorridorDTO(self):
        """Test CorridorDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CorridorDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
