"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.is_phone_available_response import IsPhoneAvailableResponse


class TestIsPhoneAvailableResponse(unittest.TestCase):
    """IsPhoneAvailableResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIsPhoneAvailableResponse(self):
        """Test IsPhoneAvailableResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IsPhoneAvailableResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
