"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.raa_s_payment_method import RaaSPaymentMethod
globals()['RaaSPaymentMethod'] = RaaSPaymentMethod
from openapi_client.model.request_money_base import RequestMoneyBase


class TestRequestMoneyBase(unittest.TestCase):
    """RequestMoneyBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestMoneyBase(self):
        """Test RequestMoneyBase"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestMoneyBase()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
