"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.raas_pre_quote_values import RaasPreQuoteValues
globals()['RaasPreQuoteValues'] = RaasPreQuoteValues
from openapi_client.model.raas_pre_quote_response import RaasPreQuoteResponse


class TestRaasPreQuoteResponse(unittest.TestCase):
    """RaasPreQuoteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRaasPreQuoteResponse(self):
        """Test RaasPreQuoteResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RaasPreQuoteResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
