"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.country_alpha2_code import CountryAlpha2Code


class TestCountryAlpha2Code(unittest.TestCase):
    """CountryAlpha2Code unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountryAlpha2Code(self):
        """Test CountryAlpha2Code"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CountryAlpha2Code()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
