"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.operation_contact_data import OperationContactData
globals()['OperationContactData'] = OperationContactData
from openapi_client.model.operation_data import OperationData


class TestOperationData(unittest.TestCase):
    """OperationData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperationData(self):
        """Test OperationData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OperationData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
