"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.inline_response403 import InlineResponse403


class TestInlineResponse403(unittest.TestCase):
    """InlineResponse403 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse403(self):
        """Test InlineResponse403"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse403()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
