"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ignored_operation_data import IgnoredOperationData
from openapi_client.model.operation_user_detail import OperationUserDetail
from openapi_client.model.payment_method_response import PaymentMethodResponse
globals()['IgnoredOperationData'] = IgnoredOperationData
globals()['OperationUserDetail'] = OperationUserDetail
globals()['PaymentMethodResponse'] = PaymentMethodResponse
from openapi_client.model.operation_detail_response import OperationDetailResponse


class TestOperationDetailResponse(unittest.TestCase):
    """OperationDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperationDetailResponse(self):
        """Test OperationDetailResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OperationDetailResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
