"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.field_errors_value import FieldErrorsValue


class TestFieldErrorsValue(unittest.TestCase):
    """FieldErrorsValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldErrorsValue(self):
        """Test FieldErrorsValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FieldErrorsValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
