"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ignored_operation_reason import IgnoredOperationReason
globals()['IgnoredOperationReason'] = IgnoredOperationReason
from openapi_client.model.ignored_operation_data import IgnoredOperationData


class TestIgnoredOperationData(unittest.TestCase):
    """IgnoredOperationData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIgnoredOperationData(self):
        """Test IgnoredOperationData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IgnoredOperationData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
