"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.update_contact_request_params import UpdateContactRequestParams


class TestUpdateContactRequestParams(unittest.TestCase):
    """UpdateContactRequestParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateContactRequestParams(self):
        """Test UpdateContactRequestParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateContactRequestParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
