"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cip_data import CIPData
globals()['CIPData'] = CIPData
from openapi_client.model.cip_document import CIPDocument


class TestCIPDocument(unittest.TestCase):
    """CIPDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCIPDocument(self):
        """Test CIPDocument"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CIPDocument()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
