"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.country_alpha2_code import CountryAlpha2Code
globals()['CountryAlpha2Code'] = CountryAlpha2Code
from openapi_client.model.create_contact_request_params_partner import CreateContactRequestParamsPartner


class TestCreateContactRequestParamsPartner(unittest.TestCase):
    """CreateContactRequestParamsPartner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateContactRequestParamsPartner(self):
        """Test CreateContactRequestParamsPartner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateContactRequestParamsPartner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
