"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.operation_user_detail import OperationUserDetail
globals()['OperationUserDetail'] = OperationUserDetail
from openapi_client.model.operation_detail import OperationDetail


class TestOperationDetail(unittest.TestCase):
    """OperationDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperationDetail(self):
        """Test OperationDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OperationDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
