"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.add_card_partner_params import AddCardPartnerParams


class TestAddCardPartnerParams(unittest.TestCase):
    """AddCardPartnerParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddCardPartnerParams(self):
        """Test AddCardPartnerParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddCardPartnerParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
