"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.field_errors import FieldErrors
globals()['FieldErrors'] = FieldErrors
from openapi_client.model.validate_error import ValidateError


class TestValidateError(unittest.TestCase):
    """ValidateError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValidateError(self):
        """Test ValidateError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ValidateError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
