"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.i_phone_info_carrier import IPhoneInfoCarrier


class TestIPhoneInfoCarrier(unittest.TestCase):
    """IPhoneInfoCarrier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIPhoneInfoCarrier(self):
        """Test IPhoneInfoCarrier"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IPhoneInfoCarrier()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
