"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_redis_status200_response import GetRedisStatus200Response


class TestGetRedisStatus200Response(unittest.TestCase):
    """GetRedisStatus200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetRedisStatus200Response(self):
        """Test GetRedisStatus200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetRedisStatus200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
