"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.send_money_response import SendMoneyResponse


class TestSendMoneyResponse(unittest.TestCase):
    """SendMoneyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendMoneyResponse(self):
        """Test SendMoneyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendMoneyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
