"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cash_location import CashLocation


class TestCashLocation(unittest.TestCase):
    """CashLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCashLocation(self):
        """Test CashLocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CashLocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
