"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.request_otp404_response import RequestOtp404Response


class TestRequestOtp404Response(unittest.TestCase):
    """RequestOtp404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestOtp404Response(self):
        """Test RequestOtp404Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestOtp404Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
