"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.available_payment_methods import AvailablePaymentMethods
from openapi_client.model.payment_token import PaymentToken
globals()['AvailablePaymentMethods'] = AvailablePaymentMethods
globals()['PaymentToken'] = PaymentToken
from openapi_client.model.raa_s_payment_method import RaaSPaymentMethod


class TestRaaSPaymentMethod(unittest.TestCase):
    """RaaSPaymentMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRaaSPaymentMethod(self):
        """Test RaaSPaymentMethod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RaaSPaymentMethod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
