# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class AuthNumiChatParams(BaseModel):
    """
    AuthNumiChatParams
    """
    device_id: StrictStr = Field(..., alias="deviceId")
    device_os: StrictStr = Field(..., alias="deviceOS")
    phone: StrictStr = Field(...)
    __properties = ["deviceId", "deviceOS", "phone"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AuthNumiChatParams:
        """Create an instance of AuthNumiChatParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AuthNumiChatParams:
        """Create an instance of AuthNumiChatParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AuthNumiChatParams.parse_obj(obj)

        _obj = AuthNumiChatParams.parse_obj({
            "device_id": obj.get("deviceId"),
            "device_os": obj.get("deviceOS"),
            "phone": obj.get("phone")
        })
        return _obj


