# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictBool
from raassdkpy.models.document_type import DocumentType
from raassdkpy.models.micro_blink_document_type import MicroBlinkDocumentType

class DocumentTypeItem(BaseModel):
    """
    DocumentTypeItem
    """
    active: StrictBool = Field(...)
    mb_type: MicroBlinkDocumentType = Field(...)
    type: DocumentType = Field(...)
    __properties = ["active", "mb_type", "type"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DocumentTypeItem:
        """Create an instance of DocumentTypeItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DocumentTypeItem:
        """Create an instance of DocumentTypeItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DocumentTypeItem.parse_obj(obj)

        _obj = DocumentTypeItem.parse_obj({
            "active": obj.get("active"),
            "mb_type": obj.get("mb_type"),
            "type": obj.get("type")
        })
        return _obj


