# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class DraftActionType(str, Enum):
    """
    DraftActionType
    """

    """
    allowed enum values
    """
    REQUEST = 'request'
    SEND = 'send'
    RECEIVE = 'receive'
    FUNDING = 'funding'

    @classmethod
    def from_json(cls, json_str: str) -> DraftActionType:
        """Create an instance of DraftActionType from a JSON string"""
        return DraftActionType(json.loads(json_str))


