# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr

class ExchangeRate(BaseModel):
    """
    tsoa_sample No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  The version of the OpenAPI document: 1.1.0 Contact: alejamp@gmail.com  NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.  # noqa: E501
    """
    id: StrictStr = Field(...)
    currency_code_dest: StrictStr = Field(..., alias="currencyCodeDest")
    currency_code_src: StrictStr = Field(..., alias="currencyCodeSrc")
    exchange_rate: Union[StrictFloat, StrictInt] = Field(..., alias="exchangeRate")
    exchange_rate_updated_at: StrictStr = Field(..., alias="exchangeRateUpdatedAt")
    __properties = ["id", "currencyCodeDest", "currencyCodeSrc", "exchangeRate", "exchangeRateUpdatedAt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ExchangeRate:
        """Create an instance of ExchangeRate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ExchangeRate:
        """Create an instance of ExchangeRate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ExchangeRate.parse_obj(obj)

        _obj = ExchangeRate.parse_obj({
            "id": obj.get("id"),
            "currency_code_dest": obj.get("currencyCodeDest"),
            "currency_code_src": obj.get("currencyCodeSrc"),
            "exchange_rate": obj.get("exchangeRate"),
            "exchange_rate_updated_at": obj.get("exchangeRateUpdatedAt")
        })
        return _obj


