# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr
from raassdkpy.models.ads import Ads

class IAds(BaseModel):
    """
    IAds
    """
    id: Optional[StrictStr] = None
    ads: Ads = Field(...)
    __properties = ["id", "ads"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IAds:
        """Create an instance of IAds from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of ads
        if self.ads:
            _dict['ads'] = self.ads.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IAds:
        """Create an instance of IAds from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IAds.parse_obj(obj)

        _obj = IAds.parse_obj({
            "id": obj.get("id"),
            "ads": Ads.from_dict(obj.get("ads")) if obj.get("ads") is not None else None
        })
        return _obj


