# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ISOCurrenciesCodes(str, Enum):
    """
    ISOCurrenciesCodes
    """

    """
    allowed enum values
    """
    MXN = 'MXN'
    USD = 'USD'
    ARS = 'ARS'
    COP = 'COP'
    HNL = 'HNL'
    PAB = 'PAB'
    GTQ = 'GTQ'
    NIO = 'NIO'
    CRC = 'CRC'
    INR = 'INR'
    PHP = 'PHP'
    DOP = 'DOP'
    CLP = 'CLP'
    PEN = 'PEN'

    @classmethod
    def from_json(cls, json_str: str) -> ISOCurrenciesCodes:
        """Create an instance of ISOCurrenciesCodes from a JSON string"""
        return ISOCurrenciesCodes(json.loads(json_str))


