# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class OCRDocumentDetail(BaseModel):
    """
    OCRDocumentDetail
    """
    document_type: Optional[StrictStr] = Field(None, alias="DocumentType")
    country: Optional[StrictStr] = Field(None, alias="Country")
    country2: Optional[StrictStr] = Field(None, alias="Country2")
    id_number: Optional[StrictStr] = Field(None, alias="IDNumber")
    full_name: Optional[StrictStr] = Field(None, alias="FullName")
    first_name: Optional[StrictStr] = Field(None, alias="FirstName")
    last_name: Optional[StrictStr] = Field(None, alias="LastName")
    second_last_name: Optional[StrictStr] = Field(None, alias="SecondLastName")
    gender: Optional[StrictStr] = Field(None, alias="Gender")
    do_b: Optional[StrictStr] = Field(None, alias="DoB")
    issue_date: Optional[StrictStr] = Field(None, alias="IssueDate")
    exp_date: Optional[StrictStr] = Field(None, alias="ExpDate")
    registrador_nacional: Optional[StrictStr] = Field(None, alias="RegistradorNacional")
    indice_derecho: Optional[StrictStr] = Field(None, alias="IndiceDerecho")
    vouch: Optional[StrictStr] = Field(None, alias="Vouch")
    estatura: Optional[StrictStr] = Field(None, alias="Estatura")
    gs_rh: Optional[StrictStr] = Field(None, alias="GS_RH")
    lugar_nacimiento: Optional[StrictStr] = Field(None, alias="LugarNacimiento")
    __properties = ["DocumentType", "Country", "Country2", "IDNumber", "FullName", "FirstName", "LastName", "SecondLastName", "Gender", "DoB", "IssueDate", "ExpDate", "RegistradorNacional", "IndiceDerecho", "Vouch", "Estatura", "GS_RH", "LugarNacimiento"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OCRDocumentDetail:
        """Create an instance of OCRDocumentDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OCRDocumentDetail:
        """Create an instance of OCRDocumentDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OCRDocumentDetail.parse_obj(obj)

        _obj = OCRDocumentDetail.parse_obj({
            "document_type": obj.get("DocumentType"),
            "country": obj.get("Country"),
            "country2": obj.get("Country2"),
            "id_number": obj.get("IDNumber"),
            "full_name": obj.get("FullName"),
            "first_name": obj.get("FirstName"),
            "last_name": obj.get("LastName"),
            "second_last_name": obj.get("SecondLastName"),
            "gender": obj.get("Gender"),
            "do_b": obj.get("DoB"),
            "issue_date": obj.get("IssueDate"),
            "exp_date": obj.get("ExpDate"),
            "registrador_nacional": obj.get("RegistradorNacional"),
            "indice_derecho": obj.get("IndiceDerecho"),
            "vouch": obj.get("Vouch"),
            "estatura": obj.get("Estatura"),
            "gs_rh": obj.get("GS_RH"),
            "lugar_nacimiento": obj.get("LugarNacimiento")
        })
        return _obj


