# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class RaasCanOperateRequest(BaseModel):
    """
    RaasCanOperateRequest
    """
    src_contry: StrictStr = Field(..., alias="srcContry")
    dest_contry: StrictStr = Field(..., alias="destContry")
    operation: StrictStr = Field(...)
    role: StrictStr = Field(..., description="User Role Sender | Requester")
    __properties = ["srcContry", "destContry", "operation", "role"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RaasCanOperateRequest:
        """Create an instance of RaasCanOperateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RaasCanOperateRequest:
        """Create an instance of RaasCanOperateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RaasCanOperateRequest.parse_obj(obj)

        _obj = RaasCanOperateRequest.parse_obj({
            "src_contry": obj.get("srcContry"),
            "dest_contry": obj.get("destContry"),
            "operation": obj.get("operation"),
            "role": obj.get("role")
        })
        return _obj


