# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictBool, StrictStr

class TemplateHeader(BaseModel):
    """
    TemplateHeader
    """
    enabled: Optional[StrictBool] = None
    version: Optional[StrictStr] = None
    lang: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    __properties = ["enabled", "version", "lang", "name", "id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TemplateHeader:
        """Create an instance of TemplateHeader from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TemplateHeader:
        """Create an instance of TemplateHeader from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TemplateHeader.parse_obj(obj)

        _obj = TemplateHeader.parse_obj({
            "enabled": obj.get("enabled"),
            "version": obj.get("version"),
            "lang": obj.get("lang"),
            "name": obj.get("name"),
            "id": obj.get("id")
        })
        return _obj


