# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TenantRaaSNotification(str, Enum):
    """
    TenantRaaSNotification
    """

    """
    allowed enum values
    """
    SMS_REQUEST_MONEY = 'SMS_Request_Money'
    SMS_SEND_MONEY = 'SMS_Send_Money'

    @classmethod
    def from_json(cls, json_str: str) -> TenantRaaSNotification:
        """Create an instance of TenantRaaSNotification from a JSON string"""
        return TenantRaaSNotification(json.loads(json_str))


