# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class UserRegisterParams(BaseModel):
    """
    UserRegisterParams
    """
    phone_number: StrictStr = Field(..., alias="phoneNumber")
    password: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    country_code: StrictStr = Field(..., alias="countryCode", description="Country code in ISO 3166-1 alpha-2 format, 2 letters, e.g. \"US\"")
    device_uid: Optional[StrictStr] = Field(None, alias="deviceUID", description="Device UID if tis possible")
    __properties = ["phoneNumber", "password", "email", "countryCode", "deviceUID"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UserRegisterParams:
        """Create an instance of UserRegisterParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UserRegisterParams:
        """Create an instance of UserRegisterParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UserRegisterParams.parse_obj(obj)

        _obj = UserRegisterParams.parse_obj({
            "phone_number": obj.get("phoneNumber"),
            "password": obj.get("password"),
            "email": obj.get("email"),
            "country_code": obj.get("countryCode"),
            "device_uid": obj.get("deviceUID")
        })
        return _obj


