"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_client.model.errors_cip_process import ErrorsCIPProcess
    from openapi_client.model.level_status import LevelStatus
    from openapi_client.model.level_status_detail import LevelStatusDetail
    from openapi_client.model.pick_cip_exclude_keyof_cipid_or_attemps_or_is_valid_ofac_lola_cip import PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP
    globals()['ErrorsCIPProcess'] = ErrorsCIPProcess
    globals()['LevelStatus'] = LevelStatus
    globals()['LevelStatusDetail'] = LevelStatusDetail
    globals()['PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP'] = PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP


class PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'cip_level': (float,),  # noqa: E501
            'has_personal_info': (bool,),  # noqa: E501
            'has_proof_of_l_ife': (bool,),  # noqa: E501
            'has_scan_ids': (bool,),  # noqa: E501
            'is_perform_level1': (bool,),  # noqa: E501
            'is_perform_level2': (bool,),  # noqa: E501
            'errors_process': (ErrorsCIPProcess,),  # noqa: E501
            'level1status': (LevelStatus,),  # noqa: E501
            'level1status_detail': (LevelStatusDetail,),  # noqa: E501
            'level2status': (LevelStatus,),  # noqa: E501
            'level2status_detail': (LevelStatusDetail,),  # noqa: E501
            'profile_and_ocr_similarity': (float,),  # noqa: E501
            'is_document_id_value_validated': (bool,),  # noqa: E501
            'is_alternate_flow': (bool,),  # noqa: E501
            'lola_cip': (PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'cip_level': 'cipLevel',  # noqa: E501
        'has_personal_info': 'hasPersonalInfo',  # noqa: E501
        'has_proof_of_l_ife': 'hasProofOfLIfe',  # noqa: E501
        'has_scan_ids': 'hasScanIds',  # noqa: E501
        'is_perform_level1': 'isPerformLevel1',  # noqa: E501
        'is_perform_level2': 'isPerformLevel2',  # noqa: E501
        'errors_process': 'errorsProcess',  # noqa: E501
        'level1status': 'level1status',  # noqa: E501
        'level1status_detail': 'level1statusDetail',  # noqa: E501
        'level2status': 'level2status',  # noqa: E501
        'level2status_detail': 'level2statusDetail',  # noqa: E501
        'profile_and_ocr_similarity': 'profileAndOCRSimilarity',  # noqa: E501
        'is_document_id_value_validated': 'isDocumentIdValueValidated',  # noqa: E501
        'is_alternate_flow': 'isAlternateFlow',  # noqa: E501
        'lola_cip': 'lolaCIP',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, cip_level, has_personal_info, has_proof_of_l_ife, has_scan_ids, is_perform_level1, is_perform_level2, errors_process, level1status, level1status_detail, level2status, level2status_detail, *args, **kwargs):  # noqa: E501
        """PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC - a model defined in OpenAPI

        Args:
            cip_level (float): this will updated  from event queue
            has_personal_info (bool):
            has_proof_of_l_ife (bool):
            has_scan_ids (bool):
            is_perform_level1 (bool):
            is_perform_level2 (bool):
            errors_process (ErrorsCIPProcess):
            level1status (LevelStatus):
            level1status_detail (LevelStatusDetail):
            level2status (LevelStatus):
            level2status_detail (LevelStatusDetail):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            profile_and_ocr_similarity (float): [optional]  # noqa: E501
            is_document_id_value_validated (bool): This will be used when the document id value will be validated. For example The Nufi's CURP validation. [optional]  # noqa: E501
            is_alternate_flow (bool): This is for knowing the specific cip has an alternate flow. [optional]  # noqa: E501
            lola_cip (PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.cip_level = cip_level
        self.has_personal_info = has_personal_info
        self.has_proof_of_l_ife = has_proof_of_l_ife
        self.has_scan_ids = has_scan_ids
        self.is_perform_level1 = is_perform_level1
        self.is_perform_level2 = is_perform_level2
        self.errors_process = errors_process
        self.level1status = level1status
        self.level1status_detail = level1status_detail
        self.level2status = level2status
        self.level2status_detail = level2status_detail
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, cip_level, has_personal_info, has_proof_of_l_ife, has_scan_ids, is_perform_level1, is_perform_level2, errors_process, level1status, level1status_detail, level2status, level2status_detail, *args, **kwargs):  # noqa: E501
        """PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC - a model defined in OpenAPI

        Args:
            cip_level (float): this will updated  from event queue
            has_personal_info (bool):
            has_proof_of_l_ife (bool):
            has_scan_ids (bool):
            is_perform_level1 (bool):
            is_perform_level2 (bool):
            errors_process (ErrorsCIPProcess):
            level1status (LevelStatus):
            level1status_detail (LevelStatusDetail):
            level2status (LevelStatus):
            level2status_detail (LevelStatusDetail):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            profile_and_ocr_similarity (float): [optional]  # noqa: E501
            is_document_id_value_validated (bool): This will be used when the document id value will be validated. For example The Nufi's CURP validation. [optional]  # noqa: E501
            is_alternate_flow (bool): This is for knowing the specific cip has an alternate flow. [optional]  # noqa: E501
            lola_cip (PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFACLolaCIP): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.cip_level = cip_level
        self.has_personal_info = has_personal_info
        self.has_proof_of_l_ife = has_proof_of_l_ife
        self.has_scan_ids = has_scan_ids
        self.is_perform_level1 = is_perform_level1
        self.is_perform_level2 = is_perform_level2
        self.errors_process = errors_process
        self.level1status = level1status
        self.level1status_detail = level1status_detail
        self.level2status = level2status
        self.level2status_detail = level2status_detail
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
