"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_client.model.cip import CIP
    from openapi_client.model.i_phone_info import IPhoneInfo
    globals()['CIP'] = CIP
    globals()['IPhoneInfo'] = IPhoneInfo


class User(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('status',): {
            'NEW': "new",
            'READY': "ready",
        },
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (str,),  # noqa: E501
            'tenant_id': (str,),  # noqa: E501
            'tenant_code': (str,),  # noqa: E501
            'email': (str,),  # noqa: E501
            'first_name': (str,),  # noqa: E501
            'last_name': (str,),  # noqa: E501
            'middle_name': (str,),  # noqa: E501
            'second_last_name': (str,),  # noqa: E501
            'address1': (str,),  # noqa: E501
            'address2': (str,),  # noqa: E501
            'place_id': (str,),  # noqa: E501
            'country': (str,),  # noqa: E501
            'address_description': (str,),  # noqa: E501
            'gender': (str,),  # noqa: E501
            'dob': (datetime,),  # noqa: E501
            'country_id': (str,),  # noqa: E501
            'status': (str,),  # noqa: E501
            'phone_number': (str,),  # noqa: E501
            'phone_verified': (bool,),  # noqa: E501
            'cip': (CIP,),  # noqa: E501
            'first_time': (bool,),  # noqa: E501
            'country_code': (str,),  # noqa: E501
            'city': (str,),  # noqa: E501
            'zipcode': (str,),  # noqa: E501
            'state': (str,),  # noqa: E501
            'birth_state': (str,),  # noqa: E501
            'place_detail': (str,),  # noqa: E501
            'pincode': (str,),  # noqa: E501
            'has_pincode': (bool,),  # noqa: E501
            'password': (str,),  # noqa: E501
            'phone_info': (IPhoneInfo,),  # noqa: E501
            'latitude': (float,),  # noqa: E501
            'longitude': (float,),  # noqa: E501
            'profile_picture_url': (str,),  # noqa: E501
            'custom_country_code': (str,),  # noqa: E501
            'facebook_public_user_name': (str,),  # noqa: E501
            'instagram_public_user_name': (str,),  # noqa: E501
            'account_code': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'tenant_id': 'tenantId',  # noqa: E501
        'tenant_code': 'tenantCode',  # noqa: E501
        'email': 'email',  # noqa: E501
        'first_name': 'firstName',  # noqa: E501
        'last_name': 'lastName',  # noqa: E501
        'middle_name': 'middleName',  # noqa: E501
        'second_last_name': 'secondLastName',  # noqa: E501
        'address1': 'address1',  # noqa: E501
        'address2': 'address2',  # noqa: E501
        'place_id': 'placeId',  # noqa: E501
        'country': 'country',  # noqa: E501
        'address_description': 'addressDescription',  # noqa: E501
        'gender': 'gender',  # noqa: E501
        'dob': 'dob',  # noqa: E501
        'country_id': 'country_id',  # noqa: E501
        'status': 'status',  # noqa: E501
        'phone_number': 'phoneNumber',  # noqa: E501
        'phone_verified': 'phoneVerified',  # noqa: E501
        'cip': 'cip',  # noqa: E501
        'first_time': 'firstTime',  # noqa: E501
        'country_code': 'countryCode',  # noqa: E501
        'city': 'city',  # noqa: E501
        'zipcode': 'zipcode',  # noqa: E501
        'state': 'state',  # noqa: E501
        'birth_state': 'birthState',  # noqa: E501
        'place_detail': 'placeDetail',  # noqa: E501
        'pincode': 'pincode',  # noqa: E501
        'has_pincode': 'hasPincode',  # noqa: E501
        'password': 'password',  # noqa: E501
        'phone_info': 'phoneInfo',  # noqa: E501
        'latitude': 'latitude',  # noqa: E501
        'longitude': 'longitude',  # noqa: E501
        'profile_picture_url': 'profilePictureUrl',  # noqa: E501
        'custom_country_code': 'customCountryCode',  # noqa: E501
        'facebook_public_user_name': 'facebookPublicUserName',  # noqa: E501
        'instagram_public_user_name': 'instagramPublicUserName',  # noqa: E501
        'account_code': 'accountCode',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, id, tenant_id, tenant_code, *args, **kwargs):  # noqa: E501
        """User - a model defined in OpenAPI

        Args:
            id (str):
            tenant_id (str):
            tenant_code (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            email (str): [optional]  # noqa: E501
            first_name (str): [optional]  # noqa: E501
            last_name (str): [optional]  # noqa: E501
            middle_name (str): [optional]  # noqa: E501
            second_last_name (str): [optional]  # noqa: E501
            address1 (str): [optional]  # noqa: E501
            address2 (str): [optional]  # noqa: E501
            place_id (str): [optional]  # noqa: E501
            country (str): [optional]  # noqa: E501
            address_description (str): Here we save some description about direcction for example: Local 304, next to the grocery store. [optional]  # noqa: E501
            gender (str): [optional]  # noqa: E501
            dob (datetime): [optional]  # noqa: E501
            country_id (str): [optional]  # noqa: E501
            status (str): [optional]  # noqa: E501
            phone_number (str): [optional]  # noqa: E501
            phone_verified (bool): [optional]  # noqa: E501
            cip (CIP): [optional]  # noqa: E501
            first_time (bool): [optional]  # noqa: E501
            country_code (str): [optional]  # noqa: E501
            city (str): [optional]  # noqa: E501
            zipcode (str): [optional]  # noqa: E501
            state (str): [optional]  # noqa: E501
            birth_state (str): [optional]  # noqa: E501
            place_detail (str): Here we save the google maps places address details. [optional]  # noqa: E501
            pincode (str): Pincode - used to validate user in Raas. [optional]  # noqa: E501
            has_pincode (bool): [optional]  # noqa: E501
            password (str): Used to store Numi Plat pincode. It's not used to validate  user in Raas. [optional]  # noqa: E501
            phone_info (IPhoneInfo): [optional]  # noqa: E501
            latitude (float): [optional]  # noqa: E501
            longitude (float): [optional]  # noqa: E501
            profile_picture_url (str): [optional]  # noqa: E501
            custom_country_code (str): [optional]  # noqa: E501
            facebook_public_user_name (str): [optional]  # noqa: E501
            instagram_public_user_name (str): [optional]  # noqa: E501
            account_code (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.id = id
        self.tenant_id = tenant_id
        self.tenant_code = tenant_code
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, id, tenant_id, tenant_code, *args, **kwargs):  # noqa: E501
        """User - a model defined in OpenAPI

        Args:
            id (str):
            tenant_id (str):
            tenant_code (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            email (str): [optional]  # noqa: E501
            first_name (str): [optional]  # noqa: E501
            last_name (str): [optional]  # noqa: E501
            middle_name (str): [optional]  # noqa: E501
            second_last_name (str): [optional]  # noqa: E501
            address1 (str): [optional]  # noqa: E501
            address2 (str): [optional]  # noqa: E501
            place_id (str): [optional]  # noqa: E501
            country (str): [optional]  # noqa: E501
            address_description (str): Here we save some description about direcction for example: Local 304, next to the grocery store. [optional]  # noqa: E501
            gender (str): [optional]  # noqa: E501
            dob (datetime): [optional]  # noqa: E501
            country_id (str): [optional]  # noqa: E501
            status (str): [optional]  # noqa: E501
            phone_number (str): [optional]  # noqa: E501
            phone_verified (bool): [optional]  # noqa: E501
            cip (CIP): [optional]  # noqa: E501
            first_time (bool): [optional]  # noqa: E501
            country_code (str): [optional]  # noqa: E501
            city (str): [optional]  # noqa: E501
            zipcode (str): [optional]  # noqa: E501
            state (str): [optional]  # noqa: E501
            birth_state (str): [optional]  # noqa: E501
            place_detail (str): Here we save the google maps places address details. [optional]  # noqa: E501
            pincode (str): Pincode - used to validate user in Raas. [optional]  # noqa: E501
            has_pincode (bool): [optional]  # noqa: E501
            password (str): Used to store Numi Plat pincode. It's not used to validate  user in Raas. [optional]  # noqa: E501
            phone_info (IPhoneInfo): [optional]  # noqa: E501
            latitude (float): [optional]  # noqa: E501
            longitude (float): [optional]  # noqa: E501
            profile_picture_url (str): [optional]  # noqa: E501
            custom_country_code (str): [optional]  # noqa: E501
            facebook_public_user_name (str): [optional]  # noqa: E501
            instagram_public_user_name (str): [optional]  # noqa: E501
            account_code (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.id = id
        self.tenant_id = tenant_id
        self.tenant_code = tenant_code
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
